steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ecom-strapi/ecom-strapi-image11', '.']
- name: node
  entrypoint: npm
  args: ['run', 'server']
- name: node
  entrypoint: npm
  args: ['run', 'client']
