steps:
- name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['up']
tags: ['cloud-builders-community']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
