steps:
- name: node
  entrypoint: npm
  args: ['run', 'server']
- name: node
  entrypoint: npm
  args: ['run', 'client']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ecom-strapi-image11', '.']
images: ['gcr.io/$PROJECT_ID/ecom-strapi-image11']
