version: '2.1'

services:
  client:
    build: .
    volumes: 
      - "./client:/app"
    environment:
      NODE_ENV: production
      LOCALHOST: localhost
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: .
    volumes: 
      - "./server:/app"
    environment:
      NODE_ENV: production
      LOCALHOST: localhost
    ports:
      - "1337:1337"
      - "27017:27017"